apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-slave-config
data:
  MYSQL_REPLICATION_MODE: slave
  MYSQL_REPLICATION_USER: repl_user
  MYSQL_REPLICATION_PASSWORD: repl_password
  MYSQL_MASTER_HOST: mysql-master
  MYSQL_MASTER_PORT_NUMBER: "3306"
  MYSQL_MASTER_ROOT_PASSWORD: master_root_password