apiVersion: v1
kind: Pod
metadata:
  name: pod-not-share-volume
spec:
  containers:
  - name: web-server
    image: nginx:alpine
    resources:
      limits:
        cpu: 200m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 200Mi
    ports:
    - containerPort:  80
      name:  http