server:
  port : ${SERVER_PORT:8080}

spring:
  datasource:
    company:
      url: ${MYSQL_URL:jdbc:mysql://localhost:3306/company}
      driverClassName: com.mysql.jdbc.Driver
      username: ${MYSQL_USERNAME:company}
      password: ${MYSQL_PASSWORD:company}
      platform: mysql
    employee:
      url: ${MYSQL_URL:jdbc:mysql://localhost:3306/employee}
      driverClassName: com.mysql.jdbc.Driver
      username: ${MYSQL_USERNAME:employee}
      password: ${MYSQL_PASSWORD:employee}
      platform: mysql
    jwt:
      driverClassName: com.mysql.jdbc.Driver
      url: ${MYSQL_URL:jdbc:mysql://localhost:3306/jwt_auth}
      username: ${MYSQL_USERNAME:jwt_auth}
      password: ${MYSQL_PASSWORD:jwtAuth}
  jpa:
    hibernate.ddl-auto: none
    generate-ddl: false
    show-sql: true

app:
  jwtSecret: J81rCZNLDq
  jwtExpirationInMs: 18000

backend-security:
  enabled: ${SECURITY_ENABLE:true}
  api-matcher:
    - /auth/**
    - /public/**
  cors:
    allowed-origins: ${ALLOWED_ORIGINS:*}
    allowed-headers: ${ALLOWED_HEADER:*}
    allowed-methods: ${ALLOWED_METHODS:GET,POST,PUT,PATCH,DELETE,OPTIONS}
    max-age: ${MAX_AGE:3600}
