apiVersion: v1
kind: Pod
metadata:
  name: demo-liveness-probe
spec:
  containers:
  - name: demo-liveness-probe
    image: thanhnb1/demo:latest
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
    - containerPort: 8080
    livenessProbe:
      # httpGet:
      #   path: /healCheck/getStatus1
      #   port: 8080
      
      httpGet:
        path: /healCheck/getStatus2
        port: 8080