apiVersion: v1
kind: Pod
metadata:
  name: demo-service-2
  labels:
    app: demo-service-2
spec:
  containers:
  - name: demo-service-2
    image: thanhnb1/demo:v4
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
    - containerPort: 8080
    livenessProbe:
      httpGet:
        path: /healCheck/getStatus1
        port: 8080