apiVersion: apps/v1
kind: Deployment
metadata:
  name: twemproxy
spec:
  selector:
    matchLabels:
      app: twemproxy
  template:
    metadata:
      labels:
        app: twemproxy
    spec:
      containers:
      - name: twemproxy
        image: malexer/twemproxy:latest
        env:
          - name: REDIS_SERVERS
            value: redis01:6379:1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 6380
---
apiVersion: v1
kind: Service
metadata:
  name: twemproxy
spec:
  selector:
    app: twemproxy
  ports:
  - port: 6380
    targetPort: 6380
