apiVersion: v1
kind: Pod
metadata:
  name: pod-for-test
spec:
  containers:
  - name: pod-for-test
    image: thanhnb1/demo:v3
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"