apiVersion: v1
kind: Pod
metadata:
  name: mc1
spec:
  containers:
  - name: 1st
    image: nginx
    volumeMounts:
    - name: html
      mountPath: /usr/share/nginx/html
  - name: 2nd
    image: debian
    volumeMounts:
    - name: html
      mountPath: /share-volume
    command: ["/bin/sh", "-c"]
    args:
      - while true; do
          mkdir -p /share-volume/;
          echo "Container 2 write $(date +%F_%H-%M-%S)">> /share-volume/index.html;
          sleep 1;
        done
  volumes:
  - name: html
    emptyDir: {}