apiVersion: v1
kind: Pod
metadata:
  name: two-containers
spec:
  restartPolicy: Never
  containers:
  - name: nginx-container
    image: nginx
    ports:
      - containerPort: 81

  - name: alpine-container
    image: alpine:3.12