apiVersion: v1
kind: Pod
metadata:
  name: hostpath-volume
spec:
  containers:
  - name: web-server
    image: nginx:alpine
    resources:
      limits:
        cpu: 200m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 200Mi
    volumeMounts:
    - name: html-volume
      mountPath: /usr/share/nginx/html
  volumes:
    - name: html-volume
      hostPath:
        path: /home/nbt/thanhnb/study/html-volume
  restartPolicy: Always