apiVersion: apps/v1
kind: Deployment
metadata:
  name: rolling-update
  labels:
    app: rolling-update
spec:
  selector:
    matchLabels:
      app: rolling-update
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 2
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: rolling-update
    spec:
      containers:
      - name: rolling-update
        image: thanhnb1/demo:v3
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
      restartPolicy: Always