version: "3.7"

services:
    db:
        image: mysql:5.7
        restart: always
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: test
        volumes:
            - mysql_data:/var/lib/mysql

#volumes
volumes:
    mysql_data: