apiVersion: v1
kind: Pod
metadata:
  name: demo-secret
  namespace: secret
  labels:
    app: demo-secret
spec:
  containers:
  - name: demo-secret
    image: "thanhnb1/demo:config-map"
    resources:
      limits:
        cpu: 200m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 200Mi
    env:
    - name: MESSAGE
      valueFrom:
        secretKeyRef:
          name: mysecret
          key: MESSAGE
    ports:
    - containerPort: 8080
      name: http