apiVersion: v1
kind: Pod
metadata:
  name: secret-as-volume
  namespace: secret
  labels:
    app: secret-as-volume
spec:
  containers:
  - name: secret-as-volume
    image: "thanhnb1/demo:secret"
    resources:
      limits:
        cpu: 200m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 200Mi
    ports:
    - containerPort: 8080
      name: http
    volumeMounts:
      - mountPath: /etc/secrets
        name: secret-config
        readOnly: true
  volumes:
    - name: secret-config
      secret:
        secretName: secret-as-volume